### ISSUE TITLE
Review the the parametes file and validate if moving to yaml is a good solution

### ISSUE THREAD

**Issue by brunohcfaria** [Radio-Spectrum/SHARC#20]

**Comment by alvimpaulo** [comment]
According to my research, the benefits of changing to yaml are:

- We could simplify the base parameter classes, by using yaml, the type of each variable are defined on the configuration file, not needing to be declared again, just to get type hint capabilities. 
- We could have nested "sections", helping to encapsulate certain configurations, although this would need more refactoring.
- Values declared in yaml convert nicely to python: boolean, int, float, list all are supported, and you simply need to read a python dict, when importing it from a yaml file.
- Most people prefer to read a yaml file rather than JSON or INI files.
- Yaml has comments, much like .ini files, should we use JSON for the configuration files, we would lose this capability.

The points against using it are:

- We already have configuration files in INI form.
- The team may need to learn how to write and read files in yaml form, but it should be a couple hours maximum to learn.

**Comment by RaulMyron** [comment]
https://github.com/Radio-Spectrum/SHARC/pull/68
